all: Problem1 Problem2 Problem3 Problem4 Problem5 Problem6 Problem7 Problem8 Problem9 Problem10 Problem11 Problem12 Problem13 Problem14 Problem16 Problem17 Problem19 Problem20 Problem22 Problem24 Problem25 Problem48
clean:
	rm -v ./bin/*.class
	rm -v ./bin/counting_sundays/*.class
	rm -v ./bin/problem17/*.class
new: clean
	make
Problem1: /bin//bin/Problem1.class
/bin//bin/Problem1.class:
	javac -d ./bin/ Problem1.java

Problem2: /bin//bin/Problem2.class
/bin//bin/Problem2.class:
	javac -d ./bin/  Problem2.java

Problem3: /bin/Problem3.class
/bin/Problem3.class:
	javac -d ./bin/  Problem3.java

Problem4: /bin/Problem4.class
/bin/Problem4.class:
	javac -d ./bin/  Problem4.java

Problem5: /bin/Problem5.class
/bin/Problem5.class:
	javac -d ./bin/  Problem5.java

Problem6: /bin/Problem6.class
/bin/Problem6.class:
	javac -d ./bin/  Problem6.java

Problem7: /bin/Problem7.class
/bin/Problem7.class:
	javac -d ./bin/  Problem7.java

Problem8: /bin/Problem8.class
/bin/Problem8.class:
	javac -d ./bin/  Problem8.java

Problem9: /bin/Problem9.class
/bin/Problem9.class:
	javac -d ./bin/  Problem9.java

Problem10: /bin/Problem10.class
/bin/Problem10.class:
	javac -d ./bin/  Problem10.java

Problem11: /bin/Problem11.class
/bin/Problem11.class:
	javac -d ./bin/  Problem11.java

Problem12: /bin/Problem12.class
/bin/Problem12.class:
	javac -d ./bin/  Problem12.java

Problem13: /bin/Problem13.class
/bin/Problem13.class:
	javac -d ./bin/  Problem13.java

Problem14: /bin/Problem14.class
/bin/Problem14.class:
	javac -d ./bin/  Problem14.java

Problem16: /bin/Problem16.class
/bin/Problem16.class:
	javac -d ./bin/  Problem16.java

Problem17: /bin/Problem17.class
/bin/Problem17.class:
	javac -d ./bin/ ./Problem17/Numbers.java ./Problem17/Problem17.java

Problem19: /bin/Problem19.class
/bin/Problem19.class:
	javac -d ./bin/ ./counting_sundays/Day.java ./counting_sundays/DayOfWeek.java ./counting_sundays/Main.java ./counting_sundays/Month.java ./counting_sundays/Year.java

Problem20: /bin/Problem20.class
/bin/Problem20.class:
	javac -d ./bin/  Problem20.java

Problem22: /bin/Problem22.class
/bin/Problem22.class:
	javac -d ./bin/  Problem22.java

Problem24: /bin/Problem24.class
/bin/Problem24.class:
	javac -d ./bin/  Problem24.java

Problem25: /bin/Problem25.class
/bin/Problem25.class:
	javac -d ./bin/  Problem25.java
Problem48: /bin/Problem48.class
/bin/Problem48.class:
	javac -d ./bin/  Problem48.java
